"""OpenAI-compat proxy that strips reasoning_content from assistant messages
before forwarding to Bifrost. Handles streaming + non-streaming.

Tool-id rewrite: ALL tool_call_ids rewritten to 9-char hex unconditionally.
Mistral requires ^[a-zA-Z0-9]{9}$ — and since hermes uses pool names
("best"/"code") in the model field, the shim cannot tell which provider
Bifrost will pick. 9-char hex is alphanumeric and accepted by every
OpenAI-compat provider, so unconditional rewrite is safe.
"""
import hashlib
import json
import logging
import os
import re
import secrets
import time
from contextlib import asynccontextmanager

import httpx
from fastapi import FastAPI, Request
from fastapi.responses import StreamingResponse, Response, JSONResponse

BIFROST_URL = os.environ.get("BIFROST_URL", "http://bifrost:8080")
PORT = int(os.environ.get("PORT", "4002"))
# Models JSON is generated by scripts/runtime/build_models_list.py on the host
# and mounted read-only into the container at /root/.coire/models.json.
# If the file is missing (clean install, generator not yet run, mount disabled)
# we fall back to the 7 static pool names so /v1/models always answers.
MODELS_JSON_PATH = os.environ.get("MODELS_JSON_PATH", "/root/.coire/models.json")

log = logging.getLogger("shim")


@asynccontextmanager
async def lifespan(app: FastAPI):
    app.state.client = httpx.AsyncClient(
        timeout=httpx.Timeout(connect=10, read=400, write=30, pool=30),
        limits=httpx.Limits(max_keepalive_connections=50, max_connections=200),
    )
    yield
    await app.state.client.aclose()


app = FastAPI(title="bifrost-strip-shim", lifespan=lifespan)


@app.get("/health")
async def health(request: Request):
    try:
        r = await request.app.state.client.get(f"{BIFROST_URL}/api/providers", timeout=3)
        upstream_ok = r.status_code in (200, 401)
    except Exception as e:
        return JSONResponse({"shim": "ok", "bifrost": f"error: {e}"}, status_code=503)
    return {"shim": "ok", "bifrost": "ok" if upstream_ok else f"http {r.status_code}"}


_FALLBACK_POOLS = ["best", "code", "mid", "fast", "compress", "vision", "ops"]


def _load_models_doc():
    """Read models.json or return None on any failure."""
    try:
        with open(MODELS_JSON_PATH, "rb") as f:
            doc = json.load(f)
        if isinstance(doc, dict) and isinstance(doc.get("data"), list):
            return doc
    except (FileNotFoundError, json.JSONDecodeError, OSError) as e:
        log.info("models.json unavailable (%s)", e)
    return None


@app.get("/v1/models")
async def list_pool_models():
    """Default model picker — POOL ALIASES ONLY (7 entries).

    Open WebUI / hermes-agent / OpenAI-compat clients show every /v1/models
    entry in their picker. Showing all 54 direct provider/model targets
    alongside the 7 pool aliases is noise — users should pick a smart pool
    by default, not pin a specific model. Direct targets are still pinnable
    by name (bifrost accepts 'cerebras/gpt-oss-120b' etc.) and discoverable
    via /v1/models/full for power users + the dashboard.
    """
    doc = _load_models_doc()
    if doc is not None:
        # Filter to pool aliases — direct targets have a "/" in id (e.g.
        # cerebras/gpt-oss-120b); pool aliases don't (best, code, mid…).
        pools = [m for m in doc["data"] if "/" not in m.get("id", "")]
        if pools:
            return {**doc, "data": pools}
    now = int(time.time())
    return {
        "object": "list",
        "data": [{"id": p, "object": "model", "created": now, "owned_by": "coire-ansic"}
                 for p in _FALLBACK_POOLS],
    }


@app.get("/v1/models/full")
async def list_all_models():
    """Power-user / dashboard endpoint — pool aliases + every direct
    provider/model target with status tags (primary/fallback/CB/probe).
    """
    doc = _load_models_doc()
    if doc is not None:
        return doc
    return await list_pool_models()


@app.get("/stub/models")
@app.get("/api/v1/models")
@app.get("/api/tags")
async def stub_models():
    return {"object": "list", "data": []}


@app.get("/version")
async def stub_version():
    return {"version": "shim-1.0"}


def strip_reasoning(messages: list) -> list:
    cleaned = []
    for m in messages:
        if isinstance(m, dict) and m.get("role") == "assistant":
            m = {k: v for k, v in m.items() if k not in (
                "reasoning_content", "reasoning", "reasoning_details",
                "provider_specific_fields",
            )}
        cleaned.append(m)
    return cleaned


def normalize_roles(messages: list) -> list:
    """Coerce OpenAI's newer `developer` role to `system`.

    Cohere returns HTTP 422 'unrecognized role developer' and mistral 422s
    similarly. The `developer` role is an OpenAI convention some clients
    (Codex CLI etc.) emit to mark agent-controller instructions distinct
    from user-installed system prompts. For our routing we treat them as
    the same. Without this normalization every cohere/mistral request
    carrying a developer message wastes a cascade slot.
    """
    out = []
    rewrote = 0
    for m in messages:
        if isinstance(m, dict) and m.get("role") == "developer":
            m = {**m, "role": "system"}
            rewrote += 1
        out.append(m)
    if rewrote:
        log.info("normalized %d developer→system role(s)", rewrote)
    return out


def drop_orphan_tool_results(messages: list) -> list:
    """Drop role:tool messages that have no preceding assistant tool_calls.

    Pi-mono / hermes-agent occasionally constructs message history with a
    bare role:tool entry as the only or trailing message — usually when an
    op-log helper invocation is captured as a 'tool result' without the
    matching assistant call. Cerebras (and others) reject these as HTTP 400.
    Bifrost surfaces it as 'provider api error (status 400)'.

    Filter contract: a role:tool message is valid ONLY if a previous
    role:assistant message in the same history has tool_calls including
    the matching tool_call_id. Otherwise drop it. Saves the wasted RPM
    + eliminates a recurring noisy error bucket.
    """
    pending_ids: set[str] = set()
    out = []
    dropped = 0
    for m in messages:
        if not isinstance(m, dict):
            out.append(m)
            continue
        role = m.get("role")
        if role == "assistant":
            for tc in (m.get("tool_calls") or []):
                tcid = tc.get("id")
                if tcid:
                    pending_ids.add(tcid)
            out.append(m)
        elif role == "tool":
            tcid = m.get("tool_call_id")
            if tcid and tcid in pending_ids:
                pending_ids.discard(tcid)
                out.append(m)
            else:
                dropped += 1
        else:
            out.append(m)
    if dropped:
        log.warning("dropped %d orphan tool message(s) from request", dropped)
    return out


def _short_id(old: str) -> str:
    return hashlib.sha1(old.encode()).hexdigest()[:9]


# Qwen-style tool calls embed in assistant content as XML:
#   <tool_call>
#     <function=name>
#     <parameter=key>value</parameter>
#   </tool_call>
# Hermes parser only accepts OpenAI tool_calls JSON. Normalize before returning.
_QWEN_TOOL_CALL = re.compile(r"<tool_call>\s*(.*?)\s*</tool_call>", re.DOTALL)
_QWEN_FUNC = re.compile(r"<function=([^>\s]+)>")
_QWEN_PARAM = re.compile(r"<parameter=([^>\s]+)>\s*(.*?)\s*</parameter>", re.DOTALL)


def normalize_qwen_tool_calls(content: str):
    """Extract Qwen-style <tool_call> blocks. Return (cleaned_content, tool_calls_list).
    cleaned_content has tool_call blocks removed. Empty list if none found."""
    matches = _QWEN_TOOL_CALL.findall(content)
    if not matches:
        return content, []
    tool_calls = []
    for block in matches:
        fname_m = _QWEN_FUNC.search(block)
        if not fname_m:
            continue
        args = {}
        for pname, pval in _QWEN_PARAM.findall(block):
            args[pname.strip()] = pval.strip()
        tool_calls.append({
            "id": secrets.token_hex(5)[:9],
            "type": "function",
            "function": {"name": fname_m.group(1).strip(), "arguments": json.dumps(args)},
        })
    cleaned = _QWEN_TOOL_CALL.sub("", content).strip()
    return cleaned, tool_calls


def normalize_json_tool_call(content: str):
    """Llama-3 / smaller-model style: bare JSON object with `name` + `parameters`/
    `arguments` keys posted directly in content. Examples:
        {"name": "execute_code", "parameters": {"code": "print(2+2)"}}
        {"name": "search", "arguments": {"q": "..."}}
    Returns (cleaned_content, tool_calls_list)."""
    s = content.strip()
    if not (s.startswith("{") and s.endswith("}")):
        return content, []
    try:
        obj = json.loads(s)
    except json.JSONDecodeError:
        return content, []
    if not isinstance(obj, dict) or "name" not in obj:
        return content, []
    args = obj.get("arguments") or obj.get("parameters") or {}
    if not isinstance(args, (dict, str)):
        return content, []
    if isinstance(args, dict):
        args_str = json.dumps(args)
    else:
        args_str = args
    return "", [{
        "id": secrets.token_hex(5)[:9],
        "type": "function",
        "function": {"name": str(obj["name"]), "arguments": args_str},
    }]


# Reasoning-model thinking trace can leak into content. Strip <think>...</think>
# blocks (deepseek, kimi, qwen reasoning all use this convention).
_THINK_BLOCK = re.compile(r"<think>.*?</think>\s*", re.DOTALL | re.IGNORECASE)


def normalize_response(payload: dict) -> dict:
    """Strip <think> leakage and lift Qwen/JSON tool calls into tool_calls."""
    if not isinstance(payload, dict) or "choices" not in payload:
        return payload
    for ch in payload.get("choices", []):
        msg = ch.get("message")
        if not isinstance(msg, dict):
            continue
        # NOTE: do NOT strip reasoning_content / reasoning from RESPONSES.
        # Hermes uses the presence of structured reasoning to take the
        # "thinking-only prefill" recovery path. If we wipe it, hermes sees
        # an empty response and triggers the brittle nudge-retry loop. We
        # only strip reasoning from REQUEST messages (the strip_reasoning
        # function in the request path); the response is hermes' problem.
        # Strip <think>...</think> block from content (still safe — that's
        # in-band leakage, not the structured reasoning field).
        content = msg.get("content") or ""
        if "<think>" in content.lower():
            content = _THINK_BLOCK.sub("", content).strip()
            msg["content"] = content or None
        if msg.get("tool_calls"):
            continue
        if not content:
            continue
        if "<tool_call>" in content:
            cleaned, tcs = normalize_qwen_tool_calls(content)
        else:
            cleaned, tcs = normalize_json_tool_call(content)
        if tcs:
            msg["content"] = cleaned or None
            msg["tool_calls"] = tcs
            ch["finish_reason"] = "tool_calls"
            log.warning("normalized %d tool_call(s) from content", len(tcs))
    return payload


def rewrite_tool_ids(messages: list) -> list:
    out = []
    for m in messages:
        if not isinstance(m, dict):
            out.append(m)
            continue
        if m.get("role") == "assistant" and isinstance(m.get("tool_calls"), list):
            new_calls = []
            for tc in m["tool_calls"]:
                if isinstance(tc, dict) and isinstance(tc.get("id"), str) and len(tc["id"]) != 9:
                    tc = {**tc, "id": _short_id(tc["id"])}
                new_calls.append(tc)
            m = {**m, "tool_calls": new_calls}
        elif m.get("role") == "tool" and isinstance(m.get("tool_call_id"), str):
            if len(m["tool_call_id"]) != 9:
                m = {**m, "tool_call_id": _short_id(m["tool_call_id"])}
        out.append(m)
    return out


@app.api_route("/v1/{path:path}", methods=["GET", "POST", "PUT", "DELETE"])
async def proxy(path: str, request: Request):
    body = await request.body()
    headers = {k: v for k, v in request.headers.items()
               if k.lower() not in ("host", "content-length")}

    is_stream = False
    if body:
        try:
            data = json.loads(body)
        except json.JSONDecodeError as e:
            log.warning("malformed JSON body: %s", e)
            data = None
        if isinstance(data, dict) and "messages" in data:
            data["messages"] = normalize_roles(data["messages"])
            data["messages"] = strip_reasoning(data["messages"])
            data["messages"] = drop_orphan_tool_results(data["messages"])
            data["messages"] = rewrite_tool_ids(data["messages"])
            # Guard: if filtering left no messages (orphan-tool-only payload),
            # bail with 400 here instead of forwarding empty to upstream —
            # cerebras / groq / others all 400 on empty messages, which
            # burns RPM + pollutes error logs. Surfaces the client bug.
            if not data["messages"]:
                log.warning("rejecting request to %s — messages empty after filtering "
                            "(likely orphan-tool-only history from %s)",
                            data.get("model", "?"),
                            request.headers.get("user-agent", "unknown"))
                return JSONResponse(
                    {"error": {
                        "message": "strip-shim: messages list empty after filtering "
                                   "(orphan tool-result with no preceding assistant "
                                   "tool_calls). Client must include the assistant "
                                   "message that invoked this tool.",
                        "type": "invalid_request_error",
                        "code": "empty_messages_after_filter",
                    }},
                    status_code=400,
                )
            # deepseek-v4-pro on NIM hangs without enable_thinking=true.
            # Scoped to that model only — kimi-k2 breaks when extras injected.
            model = data.get("model", "")
            if "deepseek-v4-pro" in model:
                ctk = data.setdefault("chat_template_kwargs", {})
                ctk.setdefault("enable_thinking", True)
                ctk.setdefault("thinking", True)
            is_stream = bool(data.get("stream"))
            body = json.dumps(data).encode()
            headers["content-length"] = str(len(body))
        elif isinstance(data, dict):
            is_stream = bool(data.get("stream"))

    target = f"{BIFROST_URL}/v1/{path}"
    client: httpx.AsyncClient = request.app.state.client

    if is_stream:
        async def gen():
            async with client.stream(
                request.method, target, content=body, headers=headers,
                params=dict(request.query_params),
            ) as r:
                async for chunk in r.aiter_raw():
                    yield chunk
        return StreamingResponse(gen(), media_type="text/event-stream")

    r = await client.request(
        request.method, target, content=body, headers=headers,
        params=dict(request.query_params),
    )

    out_content = r.content
    out_ct = r.headers.get("content-type", "")
    if r.status_code == 200 and "application/json" in out_ct and path.endswith("chat/completions"):
        try:
            payload = json.loads(r.content)
            normalize_response(payload)
            out_content = json.dumps(payload).encode()
        except (json.JSONDecodeError, TypeError):
            pass

    return Response(
        content=out_content,
        status_code=r.status_code,
        headers={k: v for k, v in r.headers.items()
                 if k.lower() not in ("content-length", "transfer-encoding", "content-encoding")},
        media_type=out_ct or None,
    )
